include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    missing_return: error

linter:
  rules:
    - avoid_print
    - cancel_subscriptions
    - directives_ordering
    - prefer_final_locals
    - prefer_relative_imports
    - public_member_api_docs
    - sort_pub_dependencies
    - throw_in_finally
    - unnecessary_lambdas
    - use_super_parameters
